./run.sh -i pebs -b gapbs -w bc -o results/results_gapbs
./run.sh -i pebs -b gapbs -w bfs -o results/results_gapbs
./run.sh -i pebs -b gapbs -w cc -o results/results_gapbs
./run.sh -i pebs -b gapbs -w pr -o results/results_gapbs
./run.sh -i pebs -b gapbs -w sssp -o results/results_gapbs
./run.sh -i pebs -b gapbs -w tc -o results/results_gapbs
./run.sh -i pebs -b xsbench -w xsbench -o results/results_xsbench
./run.sh -i pebs -b merci -w merci -o results/results_merci
./run.sh -i pebs -b liblinear -w liblinear -o results/results_liblinear
./run.sh -i pebs -b flexkvs -w flexkvs -o results/results_flexkvs
./run.sh -i pebs -b silo -w silo -o results/results_silo
